---
title: "Distribucion de Escuelas en Corrientes"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Escuelas Secundarias Corrientes

```{r}
library(leaflet)
library(leaflet.extras)
library(readxl)
# library(sp)

datos<-read.csv("escuelas secundarias.csv") # Escuelas secundarias
leaflet(datos) %>% addTiles() %>% addProviderTiles(providers$CartoDB.Positron) %>%
  #addBootstrapDependency() %>%
  addMarkers(data=datos,
             lng=~Longitud, lat=~Latitud, 
             label=~Cueanexo,
             popup = paste0("Nombre:", as.character(datos$Cueanexo)),
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
             labelOptions = labelOptions(noHide = F,
                                         direction = 'auto'))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Escuelas Primarias Corrientes

```{r}
prima<-read_xlsx("C:/Users/Los Mourglia/Desktop/mapa/escuelas primarias.xlsx")

leaflet(datos) %>% addTiles() %>% 
  
 addCircleMarkers(data=prima,
             lng=~Longitud, lat=~Latitud,
             label=~Cueanexo,
             #icon= icons,
             popup = paste0("Nombre: ", as.character(prima$Nombre)),
             clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = F),
             labelOptions = labelOptions(noHide = F,
                                         direction = 'auto')) %>% 
 
  addDrawToolbar(
    targetGroup='datos',
    editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()))


```

### Chart C

```{r}

```

